version: '3'
services:
  postgres:
    container_name: postgres_db_accounting
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=accounting
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    ports:
    - "5432:5432"
    volumes:
    - db-data:/var/lib/postgresql/data
volumes:
  db-data:
