version: '3'
services:
  postgres:
    container_name: postgres_db_accounting
    image: novacean/postgres:latest
    environment:
      - POSTGRES_DB=bookcommunity
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
    - "5432:5432" 
